// Code generated by protoc-gen-go.
// source: model.proto
// DO NOT EDIT!

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model.proto

It has these top-level messages:
	RenderRequest
	ArcPresentation
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ArcDataFormat int32

const (
	ArcDataFormat_JSON ArcDataFormat = 0
	ArcDataFormat_ARC  ArcDataFormat = 1
	ArcDataFormat_PUML ArcDataFormat = 2
)

var ArcDataFormat_name = map[int32]string{
	0: "JSON",
	1: "ARC",
	2: "PUML",
}
var ArcDataFormat_value = map[string]int32{
	"JSON": 0,
	"ARC":  1,
	"PUML": 2,
}

func (x ArcDataFormat) String() string {
	return proto.EnumName(ArcDataFormat_name, int32(x))
}
func (ArcDataFormat) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ArcVisualFormat int32

const (
	ArcVisualFormat_PNG ArcVisualFormat = 0
	ArcVisualFormat_SVG ArcVisualFormat = 1
	ArcVisualFormat_PDF ArcVisualFormat = 3
)

var ArcVisualFormat_name = map[int32]string{
	0: "PNG",
	1: "SVG",
	3: "PDF",
}
var ArcVisualFormat_value = map[string]int32{
	"PNG": 0,
	"SVG": 1,
	"PDF": 3,
}

func (x ArcVisualFormat) String() string {
	return proto.EnumName(ArcVisualFormat_name, int32(x))
}
func (ArcVisualFormat) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RenderRequest struct {
	// Type of the data
	DataFormat ArcDataFormat `protobuf:"varint,1,opt,name=dataFormat,enum=model.ArcDataFormat" json:"dataFormat,omitempty"`
	// visualFormat of the render request
	VisualFormat ArcVisualFormat `protobuf:"varint,2,opt,name=visualFormat,enum=model.ArcVisualFormat" json:"visualFormat,omitempty"`
	// data is the raw serialized byte array of the arc data type
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *RenderRequest) Reset()                    { *m = RenderRequest{} }
func (m *RenderRequest) String() string            { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()               {}
func (*RenderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RenderRequest) GetDataFormat() ArcDataFormat {
	if m != nil {
		return m.DataFormat
	}
	return ArcDataFormat_JSON
}

func (m *RenderRequest) GetVisualFormat() ArcVisualFormat {
	if m != nil {
		return m.VisualFormat
	}
	return ArcVisualFormat_PNG
}

func (m *RenderRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ArcPresentation struct {
	// Format of the presentation
	Format ArcVisualFormat `protobuf:"varint,1,opt,name=format,enum=model.ArcVisualFormat" json:"format,omitempty"`
	// Serialized raw data to be shared
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *ArcPresentation) Reset()                    { *m = ArcPresentation{} }
func (m *ArcPresentation) String() string            { return proto.CompactTextString(m) }
func (*ArcPresentation) ProtoMessage()               {}
func (*ArcPresentation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ArcPresentation) GetFormat() ArcVisualFormat {
	if m != nil {
		return m.Format
	}
	return ArcVisualFormat_PNG
}

func (m *ArcPresentation) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RenderRequest)(nil), "model.RenderRequest")
	proto.RegisterType((*ArcPresentation)(nil), "model.ArcPresentation")
	proto.RegisterEnum("model.ArcDataFormat", ArcDataFormat_name, ArcDataFormat_value)
	proto.RegisterEnum("model.ArcVisualFormat", ArcVisualFormat_name, ArcVisualFormat_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ArcViz service

type ArcVizClient interface {
	// Render serve the presentation given the raw data and type
	Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*ArcPresentation, error)
}

type arcVizClient struct {
	cc *grpc.ClientConn
}

func NewArcVizClient(cc *grpc.ClientConn) ArcVizClient {
	return &arcVizClient{cc}
}

func (c *arcVizClient) Render(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*ArcPresentation, error) {
	out := new(ArcPresentation)
	err := grpc.Invoke(ctx, "/model.ArcViz/Render", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ArcViz service

type ArcVizServer interface {
	// Render serve the presentation given the raw data and type
	Render(context.Context, *RenderRequest) (*ArcPresentation, error)
}

func RegisterArcVizServer(s *grpc.Server, srv ArcVizServer) {
	s.RegisterService(&_ArcViz_serviceDesc, srv)
}

func _ArcViz_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArcVizServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.ArcViz/Render",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArcVizServer).Render(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ArcViz_serviceDesc = grpc.ServiceDesc{
	ServiceName: "model.ArcViz",
	HandlerType: (*ArcVizServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Render",
			Handler:    _ArcViz_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}

func init() { proto.RegisterFile("model.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0xa6, 0x32, 0x72, 0xf1,
	0x06, 0xa5, 0xe6, 0xa5, 0xa4, 0x16, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x99, 0x70,
	0x71, 0xa5, 0x24, 0x96, 0x24, 0xba, 0xe5, 0x17, 0xe5, 0x26, 0x96, 0x48, 0x30, 0x2a, 0x30, 0x6a,
	0xf0, 0x19, 0x89, 0xe8, 0x41, 0xb4, 0x3a, 0x16, 0x25, 0xbb, 0xc0, 0xe5, 0x82, 0x90, 0xd4, 0x09,
	0x59, 0x71, 0xf1, 0x94, 0x65, 0x16, 0x97, 0x26, 0xe6, 0x40, 0xf5, 0x31, 0x81, 0xf5, 0x89, 0x21,
	0xf4, 0x85, 0x21, 0xc9, 0x06, 0xa1, 0xa8, 0x15, 0x12, 0xe2, 0x62, 0x01, 0x99, 0x24, 0xc1, 0xac,
	0xc0, 0xa8, 0xc1, 0x13, 0x04, 0x66, 0x2b, 0x85, 0x72, 0xf1, 0x3b, 0x16, 0x25, 0x07, 0x14, 0xa5,
	0x16, 0xa7, 0xe6, 0x95, 0x24, 0x96, 0x64, 0xe6, 0xe7, 0x09, 0xe9, 0x71, 0xb1, 0xa5, 0x21, 0x3b,
	0x0a, 0x97, 0xe1, 0x50, 0x55, 0x70, 0x63, 0x99, 0x10, 0xc6, 0x6a, 0xe9, 0x70, 0xf1, 0xa2, 0xf8,
	0x41, 0x88, 0x83, 0x8b, 0xc5, 0x2b, 0xd8, 0xdf, 0x4f, 0x80, 0x41, 0x88, 0x9d, 0x8b, 0xd9, 0x31,
	0xc8, 0x59, 0x80, 0x11, 0x24, 0x14, 0x10, 0xea, 0xeb, 0x23, 0xc0, 0xa4, 0xa5, 0x03, 0x76, 0x04,
	0xb2, 0xe1, 0x20, 0x55, 0x01, 0x7e, 0xee, 0x10, 0xe5, 0xc1, 0x61, 0xee, 0x02, 0x8c, 0x60, 0x11,
	0x17, 0x37, 0x01, 0x66, 0x23, 0x27, 0x2e, 0x36, 0xb0, 0xea, 0x2a, 0x21, 0x0b, 0x2e, 0x36, 0x48,
	0x98, 0x0a, 0xc1, 0x02, 0x0e, 0x25, 0x88, 0xa5, 0x90, 0x5c, 0x8e, 0xec, 0x43, 0x25, 0x86, 0x24,
	0x36, 0x70, 0xe4, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x81, 0xca, 0xdf, 0xab, 0x01,
	0x00, 0x00,
}
