# This file was generated by GoReleaser. DO NOT EDIT.
class Arc < Formula
  desc "Software architecture made simple"
  homepage ""
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/koderizer/arc/releases/download/v0.0.1/arc_0.0.1_darwin_amd64.tar.gz"
    sha256 "d3c01f994bd9aef0ac1a5f4f1cbebd09b0f4295c6154ef9dcfccefe5741b1b65"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/koderizer/arc/releases/download/v0.0.1/arc_0.0.1_linux_amd64.tar.gz"
      sha256 "39693e0f0005ef46f49f5f9d25a566dd5d9d90d4b6c585d70abc793a7f58f76b"
    end
  end

  def install
    bin.install "arcli"
  end
end
