FROM golang:alpine as builder

RUN mkdir /build
WORKDIR /build
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o arcviz viz/main.go
RUN chmod 755 /build/arcviz

FROM scratch
COPY --from=builder /build/arcviz /arcviz
EXPOSE 10000
ENTRYPOINT [ "/arcviz" ]